name: filmizlemeuygulamasi
description: Film izleme ve puanlama uygulaması.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_core_web: ^2.10.0
  firebase_auth: ^5.4.0
  firebase_auth_web: ^5.8.12
  cloud_firestore: ^5.6.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
