// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyd-VYF7B8PIPBSUN8RwZxSaoZhE_qyzk',
    appId: '1:431769017748:web:f3e4411ee1051addb8c381',
    messagingSenderId: '431769017748',
    projectId: 'filmizlemeuygulamasi',
    authDomain: 'filmizlemeuygulamasi.firebaseapp.com',
    storageBucket: 'filmizlemeuygulamasi.firebasestorage.app',
    measurementId: 'G-ZET2490ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtO0vwae1vECjN-0RaM00r4azewkgwMfg',
    appId: '1:431769017748:android:2b1d168068095ab7b8c381',
    messagingSenderId: '431769017748',
    projectId: 'filmizlemeuygulamasi',
    storageBucket: 'filmizlemeuygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBYcajr1y6evj5tjWaaEzYvfbVf4p6v2M',
    appId: '1:431769017748:ios:c8ce67b4010fa054b8c381',
    messagingSenderId: '431769017748',
    projectId: 'filmizlemeuygulamasi',
    storageBucket: 'filmizlemeuygulamasi.firebasestorage.app',
    iosBundleId: 'com.mobilproje.filmizlemeuygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBYcajr1y6evj5tjWaaEzYvfbVf4p6v2M',
    appId: '1:431769017748:ios:c8ce67b4010fa054b8c381',
    messagingSenderId: '431769017748',
    projectId: 'filmizlemeuygulamasi',
    storageBucket: 'filmizlemeuygulamasi.firebasestorage.app',
    iosBundleId: 'com.mobilproje.filmizlemeuygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyd-VYF7B8PIPBSUN8RwZxSaoZhE_qyzk',
    appId: '1:431769017748:web:ec63338d7fb6a73cb8c381',
    messagingSenderId: '431769017748',
    projectId: 'filmizlemeuygulamasi',
    authDomain: 'filmizlemeuygulamasi.firebaseapp.com',
    storageBucket: 'filmizlemeuygulamasi.firebasestorage.app',
    measurementId: 'G-8L952CBYM3',
  );

}